### ISSUE TITLE
NexT 關閉特定 Page 留言板 | 老王供電站

### ISSUE THREAD

**Issue by pin-yu** [pin-yu/pin-yu.github.io#1]
https://pin-yu.github.io/2020/10/24/hexo-next-disable-comment-system/ 

 前言老王在 blog 中裝了留言系統 Disqus，不過發現在 tags 和 categories 這兩個 pages 中都有留言系統的身影，實在怪怪的，所以來研究怎麼在特定 page 關閉留言系統。

**Comment by Daviswww** [comment]
hello
